### ISSUE TITLE
Route dispatch never rendered on simple server-side route example (1.0.0)

### ISSUE THREAD

**Issue by ghost** [iron-meteor/iron-router#1029]
Just can't get the server-side routing example from the documentation to work with iron:router 1.0.0

``` coffeescript
Router.route '/hello', ->
    @response.end 'hello from the server\n'
    return
    where: 'server'
```

It throws the following exception in the console:

```
Route dispatch never rendered. Did you forget to call this.next() in an onBeforeAction?  
```

and some errors beginning with:

```
Exception in callback of async function: TypeError: undefined is not a function
```

I only have the default meteor-platform and coffeescript packages installed on meteor version 1.0.0 and iron:router@1.0.0.
