### ISSUE TITLE
Meteor 1.3 and Full App Tests throws client side error

### ISSUE THREAD

**Issue by topleft** [iron-meteor/iron-router#1527]
Iron Router has been working fine in 1.3, but...

When running: 

```
 meteor test --full-app --driver-package practicalmeteor:mocha
```

This error is thrown in the dev tools console:

```
Exception in callback of async function: TypeError: fn is not a function
    at http://localhost:4000/packages/iron_controller.js?hash=779e6519eca5017ac18aafda7cf55ad0a63cac42:123:22
    at Tracker.Computation._compute (http://localhost:4000/packages/tracker.js?hash=b267c37effdf4af331d16fc647c0370c2eaff44d:341:36)
    at new Tracker.Computation (http://localhost:4000/packages/tracker.js?hash=b267c37effdf4af331d16fc647c0370c2eaff44d:229:10)
    at Object.Tracker.autorun (http://localhost:4000/packages/tracker.js?hash=b267c37effdf4af331d16fc647c0370c2eaff44d:580:11)
    at http://localhost:4000/packages/iron_controller.js?hash=779e6519eca5017ac18aafda7cf55ad0a63cac42:121:21
    at Object.Tracker.nonreactive (http://localhost:4000/packages/tracker.js?hash=b267c37effdf4af331d16fc647c0370c2eaff44d:607:12)
    at WaitList.wait (http://localhost:4000/packages/iron_controller.js?hash=779e6519eca5017ac18aafda7cf55ad0a63cac42:114:8)
    at Controller.wait (http://localhost:4000/packages/iron_controller.js?hash=779e6519eca5017ac18aafda7cf55ad0a63cac42:430:20)
    at http://localhost:4000/packages/iron_router.js?hash=12cdff6998f386a73ca41d9ef0657cb87d411c98:425:10
    at Array.forEach (native)
```

Tests still run fine.

Any way to get rid of this? thanks
##### Versions:

Meteor 1.3.1
iron:controller@1.0.12
iron:core@1.0.11
iron:dynamic-template@1.0.12
iron:layout@1.0.12
iron:location@1.0.11
iron:middleware-stack@1.0.11
iron:router@1.0.12
iron:url@1.0.11
